default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: git_social_development

test:
  <<: *default
  database: git_social_test

production:
  <<: *default
  database: git_social_production
  username: git_social
  password: <%= ENV['GIT_SOCIAL_DATABASE_PASSWORD'] %>
